// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"

	"github.com/gbuenodev/fullcycle_go_expert/desafio03/internal/entity"
	"github.com/gbuenodev/fullcycle_go_expert/desafio03/internal/event"
	"github.com/gbuenodev/fullcycle_go_expert/desafio03/internal/infra/database"
	"github.com/gbuenodev/fullcycle_go_expert/desafio03/internal/infra/web"
	"github.com/gbuenodev/fullcycle_go_expert/desafio03/internal/usecase"
	"github.com/gbuenodev/fullcycle_go_expert/desafio03/pkg/events"

	"github.com/google/wire"

	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

// Este é um injetor para o caso de uso de criação, usado pelo gRPC e outros.
func NewCreateOrderUseCase(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *usecase.CreateOrderUseCase {
	orderRepository := database.NewOrderRepository(db)
	orderCreated := event.NewOrderCreated()
	createOrderUseCase := usecase.NewCreateOrderUseCase(orderRepository, orderCreated, eventDispatcher)
	return createOrderUseCase
}

func NewListOrdersUseCase(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *usecase.ListOrdersUseCase {
	orderRepository := database.NewOrderRepository(db)
	listOrdersUseCase := usecase.NewListOrdersUseCase(orderRepository)
	return listOrdersUseCase
}

func NewWebOrderHandler(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *web.WebOrderHandler {
	orderRepository := database.NewOrderRepository(db)
	orderCreated := event.NewOrderCreated()
	createOrderUseCase := usecase.NewCreateOrderUseCase(orderRepository, orderCreated, eventDispatcher)
	listOrdersUseCase := usecase.NewListOrdersUseCase(orderRepository)
	webOrderHandler := web.NewWebOrderHandler(createOrderUseCase, listOrdersUseCase)
	return webOrderHandler
}

// wire.go:

var setOrderRepositoryDependency = wire.NewSet(database.NewOrderRepository, wire.Bind(new(entity.OrderRepositoryInterface), new(*database.OrderRepository)))

var setEventDispatcherDependency = wire.NewSet(events.NewEventDispatcher, wire.Bind(new(events.EventDispatcherInterface), new(*events.EventDispatcher)))

var setOrderCreatedEvent = wire.NewSet(event.NewOrderCreated, wire.Bind(new(events.EventInterface), new(*event.OrderCreated)))
