// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gbuenodev/fullcycle_go_expert/desafio04/backend/config"
	"github.com/gbuenodev/fullcycle_go_expert/desafio04/backend/internal/infra/api"
	"github.com/gbuenodev/fullcycle_go_expert/desafio04/backend/internal/infra/clients"
	"github.com/gbuenodev/fullcycle_go_expert/desafio04/backend/internal/infra/webserver"
	"github.com/gbuenodev/fullcycle_go_expert/desafio04/backend/internal/usecase"
	"github.com/go-chi/chi/v5"
)

// Injectors from wire.go:

func InitializeWebServer(cfg *config.Config) (*webserver.WebServer, error) {
	viaCEPClient := provideViaCEPClient(cfg)
	weatherAPIClient := provideWeatherAPIClient(cfg)
	getWeatherUseCase := usecase.NewGetWeatherUseCase(viaCEPClient, weatherAPIClient)
	weatherHandler := api.NewWeatherHandler(getWeatherUseCase)
	router := webserver.NewRouter(weatherHandler)
	mux := provideChiRouter(router)
	webServer := provideWebServer(cfg, mux)
	return webServer, nil
}

// wire.go:

func provideViaCEPClient(cfg *config.Config) *clients.ViaCEPClient {
	return clients.NewViaCEPClient(cfg.ViaCEP.BaseURL)
}

func provideWeatherAPIClient(cfg *config.Config) *clients.WeatherAPIClient {
	return clients.NewWeatherAPIClient(cfg.WeatherAPI.BaseURL, cfg.WeatherAPI.Key)
}

func provideChiRouter(router *webserver.Router) *chi.Mux {
	return router.SetupRoutes()
}

func provideWebServer(cfg *config.Config, chiRouter *chi.Mux) *webserver.WebServer {
	return webserver.NewWebServer(chiRouter, cfg.Server.Port)
}
